[project]
name = "wo"
dynamic = ["version"]
dependencies = [
"lief==0.15.1"
]

[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
wo = "wo.wo:main_cli"
